#!/usr/bin/env python3
"""Regenerate ../firewall/proxy-ips.txt from public proxy lists.

  python3 refresh-ips.py          fast: plain IP:port lists only  (~4k IPs)
  python3 refresh-ips.py --full   also pull v2ray/vless configs   (~43k IPs, ~200MB download)

Filters out, in this order:
  1. anything matching ip-allowlist.txt      (Anthropic, your VPN, ...)
  2. loopback / RFC1918 / link-local / multicast   (blocking these breaks your LAN)
  3. CDN and public-resolver ranges          (one IP fronts thousands of sites)
"""
import base64, ipaddress, json, os, re, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "firewall", "proxy-ips.txt")
FULL = "--full" in sys.argv

RAW = "https://raw.githubusercontent.com"
SOURCES = [
    f"{RAW}/iplocate/free-proxy-list/main/all-proxies.txt",
    f"{RAW}/proxifly/free-proxy-list/main/proxies/all/data.txt",
]
FULL_SOURCES = [
    f"{RAW}/ebrasha/free-v2ray-public-list/main/vmess_configs.txt",
    f"{RAW}/ebrasha/free-v2ray-public-list/main/vless_configs.txt",
    f"{RAW}/ebrasha/free-v2ray-public-list/main/trojan_configs.txt",
    f"{RAW}/ebrasha/free-v2ray-public-list/main/ss_configs.txt",
]

IPP = re.compile(r"\b((?:[0-9]{1,3}\.){3}[0-9]{1,3}):([0-9]{1,5})\b")
VMESS = re.compile(r"vmess://([A-Za-z0-9+/=_-]+)")

# One IP here can front thousands of unrelated sites. Never block them.
CDN = re.compile(r"""^(
 104\.(1[6-9]|2[0-9]|3[01])\.|172\.(6[4-9]|7[01])\.|162\.159\.|173\.245\.4[89]\.
|188\.114\.9[6-9]\.|190\.93\.24[0-3]\.|198\.41\.1(2[89]|3[0-9]|4[0-3])\.
|103\.21\.24[4-7]\.|103\.22\.20[0-3]\.|103\.31\.[4-7]\.|131\.0\.7[2-5]\.
|141\.101\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.|108\.162\.(19[2-9]|2[0-5][0-9])\.
|151\.101\.|199\.232\.
|(3|13|18|52|54)\.|(34|35)\.
|(2[03])\.(3[0-9]|[4-9][0-9]|1[0-9][0-9])\.
|8\.8\.|1\.1\.1\.|1\.0\.0\.|9\.9\.9\.|208\.67\.22[02]\.
)""", re.X)


def allow_prefixes():
    p = os.path.join(HERE, "ip-allowlist.txt")
    out = []
    for line in open(p):
        s = line.split("#")[0].strip()
        if s:
            out.append(s)
    return tuple(out)


def valid(ip, port):
    o = ip.split(".")
    return (all(x.isdigit() and int(x) < 256 and x == str(int(x)) for x in o)
            and 0 < int(port) < 65536)


def routable(ip):
    try:
        a = ipaddress.ip_address(ip)
    except ValueError:
        return False
    return a.is_global and not a.is_multicast


def vmess_hosts(line):
    """vmess:// payloads are base64 JSON; the endpoint is hidden inside."""
    for b in VMESS.findall(line):
        try:
            j = json.loads(base64.b64decode(b + "=" * (-len(b) % 4)))
        except Exception:
            continue
        add, port = str(j.get("add", "")), str(j.get("port", ""))
        if add and port and IPP.fullmatch(f"{add}:{port}"):
            yield add, port


def main():
    allow = allow_prefixes()
    urls = SOURCES + (FULL_SOURCES if FULL else [])
    ips = set()
    for u in urls:
        try:
            with urllib.request.urlopen(u, timeout=120) as r:
                data = r.read().decode("utf-8", "ignore")
        except Exception as e:
            print(f"  SKIP {u.rsplit('/',1)[-1]}: {e}")
            continue
        before = len(ips)
        for line in data.splitlines():
            for ip, port in IPP.findall(line):
                if valid(ip, port):
                    ips.add(ip)
            for ip, port in vmess_hosts(line):
                if valid(ip, port):
                    ips.add(ip)
        print(f"  {u.rsplit('/',1)[-1]:32} +{len(ips)-before}")

    keep, drop_allow, drop_priv, drop_cdn = [], 0, 0, 0
    for ip in sorted(ips, key=lambda s: tuple(int(x) for x in s.split("."))):
        if ip.startswith(allow):
            drop_allow += 1
        elif not routable(ip):
            drop_priv += 1
        elif CDN.match(ip):
            drop_cdn += 1
        else:
            keep.append(ip)

    # Refuse to ship a list that would cut this machine off from Anthropic.
    assert not any(i.startswith("160.79.") for i in keep), "Anthropic IPs leaked in"

    # Refuse to destroy the existing list when every source failed (offline, etc).
    if not keep:
        sys.exit(f"ABORT: 0 IPs kept -- refusing to overwrite {os.path.normpath(OUT)}")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT + ".tmp", "w") as f:
        f.write("# Title: Proxy endpoint IPs\n")
        f.write("# Description: NOT a Pi-hole list. Firewall use only (pf/iptables/router ACL).\n")
        f.write("# Source: scraped free-proxy lists; allowlist, private and CDN ranges removed\n")
        f.write("# Generated by local-mac/refresh-ips.py\n")
        f.write("# WARNING: scraped data. Verify against your own critical hosts before loading.\n#\n")
        f.write("\n".join(keep) + "\n")
    os.replace(OUT + ".tmp", OUT)

    print(f"\n{len(ips)} scraped -> {len(keep)} kept")
    print(f"  dropped: {drop_allow} allowlisted, {drop_priv} private/loopback, {drop_cdn} CDN/resolver")
    print(f"wrote {os.path.normpath(OUT)}")
    if not FULL:
        print("(fast mode: rerun with --full for the v2ray sources, ~10x more IPs)")


if __name__ == "__main__":
    main()
