#!/usr/bin/env python3
"""Fetch hagezi's doh-vpn-proxy-bypass domains for /etc/hosts use.

LOCAL-MAC ONLY. Pi-hole users don't need this: subscribe to hagezi as an
adlist instead (see README.md "Scope"). This exists because /etc/hosts can't
subscribe to anything, so the upstream list has to be fetched and expanded.

Writes local-mac/upstream-hosts.txt: hagezi's ~18k wildcard domains,
prefix-expanded so a wildcard-less /etc/hosts still catches the common
subdomains. macblock.sh hosts-on appends this file when it exists.

Gitignored on purpose -- hagezi updates weekly, so fetch it, don't vendor it.
"""
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools"))
import lists

URL = ("https://raw.githubusercontent.com/hagezi/dns-blocklists/main/"
       "wildcard/doh-vpn-proxy-bypass-onlydomains.txt")
OUT = os.path.join(HERE, "upstream-hosts.txt")

# Deliberately smaller than lists.PREFIXES: the full set would balloon ~18k
# base domains to ~600k /etc/hosts lines. These cover what people actually hit.
PREFIXES = "www free proxy blog app my web".split()


def main():
    try:
        with urllib.request.urlopen(URL, timeout=120) as r:
            data = r.read().decode("utf-8", "ignore")
    except Exception as e:
        sys.exit(f"ABORT: fetch failed ({e}) -- {os.path.normpath(OUT)} left untouched")

    base = sorted({s for s in (l.split("#")[0].strip().lower() for l in data.splitlines())
                   if s and lists.DOMAIN_RE.match(s)})
    if not base:
        sys.exit(f"ABORT: 0 domains parsed -- refusing to write {os.path.normpath(OUT)}")

    # Never block a critical or allowlisted host, nor anything beneath one.
    protected = set(lists.read("allowlist.txt")) | set(lists.CRITICAL)

    def safe(d):
        return d not in protected and not any(d.endswith("." + p) for p in protected)

    out = set()
    for d in base:
        if not safe(d):
            continue
        out.add(d)
        if lists.is_registrable(d):
            out.update(f"{p}.{d}" for p in PREFIXES)
    out = sorted(out)

    with open(OUT + ".tmp", "w") as f:
        f.write("# Title: Upstream hosts (hagezi doh-vpn-proxy-bypass, prefix-expanded)\n")
        f.write(f"# Source: {URL}\n")
        f.write(f"# Entries: {len(out)}\n")
        f.write("# Generated by local-mac/refresh-upstream.py -- do not edit, do not commit\n")
        f.write("\n".join(out) + "\n")
    os.replace(OUT + ".tmp", OUT)
    print(f"{len(base)} base domains -> {len(out)} hostnames -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
