#!/usr/bin/env python3
"""Regenerate the derived files from the hand-edited *-sites.txt lists.

  regex.txt        wildcard patterns for Pi-hole's regex table (CLI/UI only)
  expanded/*.txt   subdomain-expanded hostnames, subscribable as adlist URLs
  firewall/*.txt   left alone here -- see local-mac/refresh-ips.py

The source of truth is one bare domain per line. Everything else is a mechanical
derivation of it; without a build step you maintain three files and they drift.
The sources themselves are sorted in place too, so appending a domain
anywhere and running build is enough.

  python3 tools/build.py          rebuild everything
  python3 tools/build.py --check  fail if anything is out of date (no writes)
"""
import datetime
import os
import re
import sys

import lists as L

CHECK = "--check" in sys.argv
STALE = []


DATE_LINE = re.compile(r"^# Last updated: .*$", flags=re.M)


def emit(rel, text):
    """Write unless --check, in which case just record a mismatch.

    A file whose only difference is the '# Last updated:' stamp is left
    alone -- otherwise every build on a new day rewrites every derived
    file, and two machines fight over date-only diffs forever.
    """
    p = L.path(rel)
    old = open(p).read() if os.path.exists(p) else None
    if old is not None and DATE_LINE.sub("", old) == DATE_LINE.sub("", text):
        return False
    if CHECK:
        STALE.append(rel)
        return True
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w") as f:
        f.write(text)
    return True


def header(title, desc, extra=()):
    today = datetime.date.today().isoformat()
    out = [f"# Title: {title}", f"# Description: {desc}",
           "# Format: domain-per-line (Pi-hole adlist compatible)",
           f"# Last updated: {today}",
           "# Generated by tools/build.py -- do not edit by hand", "#"]
    out += [f"# {l}" for l in extra]
    if extra:
        out.append("#")
    return out


def build_regex():
    out = ["# Title: Wildcard regex blocklist",
           r"# Description: (\.|^)domain$ patterns -- covers every subdomain",
           "# Format: Pi-hole regex (Admin -> Domains -> Regex, or 'pihole regex <pattern>')",
           f"# Last updated: {datetime.date.today().isoformat()}",
           "# Generated by tools/build.py -- do not edit by hand", "#"]
    n = 0
    for f in L.CORE_LISTS:
        out.append(f"# --- from {f} ---")
        for d in sorted(set(L.read(f))):
            out.append(L.regex_for(d))
            n += 1
    emit("regex.txt", "\n".join(out) + "\n")
    return n


def build_expanded():
    counts = {}
    for f in L.ALL_LISTS:
        base = sorted(set(L.read(f)))
        hosts = set(base)
        for d in base:
            # Only expand registrable names -- see lists.is_registrable.
            if L.is_registrable(d):
                hosts.update(f"{p}.{d}" for p in L.PREFIXES)
        body = header(
            f"{f[:-4]} (subdomain-expanded)",
            f"every domain in {f} plus common host prefixes",
            extra=[f"Source list: {f} -- edit that, not this file.",
                   "Exact match only. Does NOT cover subdomains outside the prefix set.",
                   "For full wildcard coverage add regex.txt to Pi-hole's regex table."],
        ) + sorted(hosts)
        emit(L.expanded_name(f), "\n".join(body) + "\n")
        counts[f] = len(hosts)
    return counts


def normalize_sources():
    """Sort each source list's domains in place.

    Comment and blank lines stay where they are; each contiguous run of
    domain lines between them is sorted in place, so hand-appended entries
    land in order without touching sections like temp-email's commented-out
    "Aggressive" block.
    """
    for f in L.ALL_LISTS:
        p = L.path(f)
        txt = open(p).read()
        out, run = [], []
        for line in txt.splitlines() + [None]:  # sentinel flushes the last run
            if line is not None and line.split("#")[0].strip():
                run.append(line)
            else:
                out.extend(sorted(run))
                run = []
                if line is not None:
                    out.append(line)
        new = "\n".join(out) + "\n"
        if new != txt:
            if CHECK:
                STALE.append(f"{f} (sorting)")
            else:
                open(p, "w").write(new)


def main():
    normalize_sources()
    n_re = build_regex()
    counts = build_expanded()

    print(f"regex.txt{'':22} {n_re:6} patterns")
    for f, n in counts.items():
        print(f"{L.expanded_name(f):31} {n:6} hostnames")

    ips = L.path("firewall/proxy-ips.txt")
    if os.path.exists(ips):
        n = len([l for l in open(ips) if not l.startswith("#") and l.strip()])
        print(f"{'firewall/proxy-ips.txt':31} {n:6} addresses (refresh: local-mac/refresh-ips.py)")

    if CHECK:
        if STALE:
            print("\nOUT OF DATE:")
            for s in STALE:
                print("  ", s)
            print("run: python3 tools/build.py")
            sys.exit(1)
        print("\nup to date")
    else:
        print("\nBuilt. Now run: python3 tools/qa.py")


if __name__ == "__main__":
    main()
